In [3]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

corrected_temperature = temperature + 2
fahrenheit = corrected_temperature * 9 / 5 + 32
above_32 = corrected_temperature[corrected_temperature > 32]
count_above_32 = np.sum(corrected_temperature > 32)

print("Corrected temperatures:", corrected_temperature)
print("Fahrenheit:", fahrenheit)
print("Readings above 32°C:", above_32)
print("Count above 32°C:", count_above_32)
print("Vectorization applies operations to the entire array efficiently.")
print("Boolean indexing selects values that satisfy a condition without loops.")    





Corrected temperatures: [27 30 33 37 40 29 35 42]
Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings above 32°C: [33 37 40 35 42]
Count above 32°C: 5
Vectorization applies operations to the entire array efficiently.
Boolean indexing selects values that satisfy a condition without loops.


In [4]:
#Q2
import numpy as np
steps = np.array([

    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print("\nQ2")
print("Total steps:", np.sum(steps))
print("Mean steps:", np.mean(steps))
print("Maximum steps:", np.max(steps))
print("Minimum steps:", np.min(steps))
print("Total steps per day:", np.sum(steps, axis=0))
print("Total steps per user:", np.sum(steps, axis=1))

max_position = np.unravel_index(np.argmax(steps), steps.shape)
print("Maximum value position (user, day):", max_position)
print("Maximum value:", steps[max_position])



Q2
Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps per day: [26500 27300 30400]
Total steps per user: [18300 24500 14400 27000]
Maximum value position (user, day): (np.int64(3), np.int64(2))
Maximum value: 9500


In [5]:
# Q3
import numpy as np
original = np.array([1, 2, 3, 4, 5, 6])

subset = original[1:5]
subset[0] = 999

print("\nQ3")
print("Original after modifying slice:", original)
print("Subset:", subset)

copied_subset = original[1:5].copy()
copied_subset[0] = 500

print("Original after modifying copied slice:", original)
print("Copied array:", copied_subset)

matrix = np.arange(1, 13).reshape(3, 4)
print("3 × 4 matrix:\n", matrix)

print("First row:", matrix[0])
print("Last row:", matrix[-1])
print("Second column:", matrix[:, 1])
print("Rows 1–2 and columns 2–3:\n", matrix[1:3, 2:4])

flattened = matrix.flatten()
raveled = matrix.ravel()

raveled[0] = 100
print("Matrix after modifying ravel():\n", matrix)
print("Raveled array:", raveled)

flattened[1] = 200
print("Matrix after modifying flatten():\n", matrix)
print("Flattened array:", flattened)

print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)


Q3
Original after modifying slice: [  1 999   3   4   5   6]
Subset: [999   3   4   5]
Original after modifying copied slice: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]
3 × 4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1–2 and columns 2–3:
 [[ 7  8]
 [11 12]]
Matrix after modifying ravel():
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Raveled array: [100   2   3   4   5   6   7   8   9  10  11  12]
Matrix after modifying flatten():
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Flattened array: [  1 200   3   4   5   6   7   8   9  10  11  12]
Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [6]:
# Q4
import numpy as np
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("\nQ4")
print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

XT = X.T
print("X.T:\n", XT)
print("The transpose changes rows into columns, so each feature becomes a row.")

XTX = XT @ X
print("X.T @ X:\n", XTX)

XTX_inverse = np.linalg.inv(XTX)
print("Inverse of X.T @ X:\n", XTX_inverse)

beta = XTX_inverse @ XT @ y
print("OLS coefficients:", beta)
print("The coefficients represent the contribution of sleep, activity, and stress.")

new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print("Predicted assistance score:", predicted_score)


Q4
Shape of X: (4, 3)
Dimensions of X: 2
X.T:
 [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
The transpose changes rows into columns, so each feature becomes a row.
X.T @ X:
 [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Inverse of X.T @ X:
 [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
OLS coefficients: [-0.15921454  0.14083853 10.06302242]
The coefficients represent the contribution of sleep, activity, and stress.
Predicted assistance score: 75.27862544778861
